publicWelcomeMessage: "&6Bienvenue {player}! Tu es le joueur n\u00B0{count} \u00E0 te connecter sur BTE France!"

privateWelcomeMessage:
- "&3-------------------------------------------"
- "&6Bienvenue sur BTE France, {player}! Si tu es nouveau, merci de lire le channel #comment-rejoindre sur Discord!"
- " "
- "&6Welcome to BTE France, {player}! If you are new here, please read the #how-to-join Discord channel"
- " "
- "&6Joueurs en ligne / Online players: &c{online}"
- "&3-------------------------------------------"

schematicSync:
  webDirectoryPath: ""
  urlRoot: "https://example.com"
  salt: "CHANGE_THIS_AND_KEEP_IT_SECRET"
  channelId: 0
  nominatimUserAgent: "BTE France Minecraft plugin"
  nominatimEndpoint: "https://nominatim.openstreetmap.org/"
  nominatimEmail: "example@example.com"
  thumbnail: "https://i.imgur.com/1ZPB2Wt.png"
  embed:
    title: "New schematic!"
    description: "{user} created a new schematic!"
    fields:
      url:
        name: "Download link:"
        pattern: "{url}"
        inline: false
      address:
        name: "Address:"
        pattern: "{address}"
        inline: false
      size:
        name: "File size:"
        pattern: "{size}"
        inline: true