name: BTEFranceUtils
author: mAxYoLo01
version: 1.0
main: fr.maxyolo01.btefranceutils.Main
description: BTE France custom plugin
commands:
    btefrance:
        description: BTE France command
    banroulette:
        description: Ban roulette with currently connected players